# This is a config file containing experiment runs to be used for hyperparameter searching

# WandB names
wandb:
  project: MTQE
  entity: turing-arc

# The experiments defined in this file will be run once for each of the following seeds
seeds:
  - 385

# Any params for the slurm file that will be the same across all experiments
slurm:
  account: vjgo8416-mt-qual-est

# These are model parameters that are fixed for each experiment
hparams:
  activations: Tanh
  class_identifier: ced_model
  encoder_model: XLM-RoBERTa
  exclude_outliers: 300
  hidden_sizes:
  - 3072
  - 1024
  input_segments:
  - mt
  - src
  layer: mix
  layer_norm: true
  layer_transformation: sparsemax
  layerwise_decay: 0.95
  loss_lambda: 0.65
  nr_frozen_epochs: 0
  optimizer: AdamW
  pool: avg
  pretrained_model: microsoft/infoxlm-large
  sent_layer: mix
  word_layer: 24
  word_level_training: false
  batch_size: 32
  learning_rate: 1.0e-05
  encoder_learning_rate: 1.0e-06
  dropout: 0.1
  loss: binary_cross_entropy_with_logits
  keep_embeddings_frozen: false
  oversample_minority: true

model_checkpoint:
  monitor: val_MCC
  save_weights_only: true
  save_top_k: 1
  mode: max
  save_last: true

# This is trainer config that is fixed for all experiments
trainer_config:
  deterministic: True
  devices: 1
  max_epochs: 100
  accumulate_grad_batches: 8
  reload_dataloaders_every_n_epochs: 1
  num_sanity_val_steps: 0

# These are the data for each experiment
experiments:
  base_auth:
    name: base_auth
    train_data:
      train_1:
        dataset_name: multilingual_ced
        language_pairs:
          - all
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
          - en-de
          - en-zh
          - en-ja
    slurm:
      memory: 40G
      time: '12:00:00'
  base_demetr:
    name: base_demetr
    train_data:
      train_1:
        dataset_name: demetr
        language_pairs:
          - all
    dev_data:
      dev_1:
        dataset_name: demetr
        language_pairs:
          - all
    slurm:
      memory: 40G
      time: '24:00:00'
  base_demetr_auth:
    name: base_demetr_auth
    train_data:
      train_1:
        dataset_name: all_multilingual_demetr
        language_pairs:
          - all
    dev_data:
      dev_1:
        dataset_name: all_multilingual_demetr
        language_pairs:
          - en-cs
          - en-de
          - en-ja
          - en-zh
    slurm:
      memory: 40G
      time: '48:00:00'
  base_wmt22_en_de:
    name: base_wmt22_en_de
    train_data:
      train_1:
        dataset_name: wmt22_ende_ced_reduced
        language_pairs:
          - en_de
    dev_data:
      dev_1:
        dataset_name: wmt22_ende_ced
        language_pairs:
          - en_de
    slurm:
      memory: 40G
      time: '24:00:00'
  base_wmt22_en_de_small:
    name: base_wmt22_en_de_small
    train_data:
      train_1:
        dataset_name: wmt22_ende_ced_small
        language_pairs:
          - en_de
    dev_data:
      dev_1:
        dataset_name: wmt22_ende_ced
        language_pairs:
          - en_de
    slurm:
      memory: 40G
      time: '24:00:00'
