# This is a config file containing experiment runs to be used for hyperparameter searching

# WandB names
wandb:
  project: MTQE
  entity: turing-arc

# The experiments defined in this file will be run once for each of the following seeds
seeds:
  - 42

# Any params for the slurm file that will be the same across all experiments
slurm:
  account: vjgo8416-mt-qual-est

# These are model parameters that are fixed for each experiment
hparams:
  activations: Tanh
  class_identifier: ced_model
  dropout: 0.1
  encoder_learning_rate: 1.0e-06
  encoder_model: XLM-RoBERTa
  final_activation: sigmoid
  hidden_sizes:
  - 3072
  - 1024
  input_segments:
  - mt
  - src
  layer: mix
  layer_norm: false
  layer_transformation: sparsemax
  layerwise_decay: 0.95
  learning_rate: 1.5e-05
  loss: cross-entropy
  loss_lambda: 0.65
  keep_embeddings_frozen: true
  nr_frozen_epochs: 0.3
  optimizer: AdamW
  pool: avg
  pretrained_model: microsoft/infoxlm-large
  sent_layer: mix
  word_layer: 24
  word_level_training: false

# This is trainer config that is fixed for each experiment
trainer_config:
  deterministic: True
  devices: 1
  max_epochs: 100

# These are the data for each experiment
experiments:
  en-cs_hparams_1a:
    name: en-cs_hparams_1a
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      batch_size: 256
    slurm:
      memory: 40G
      time: 05:00:00
  en-cs_hparams_1b:
    name: en-cs_hparams_1b
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      batch_size: 128
    slurm:
      memory: 40G
      time: 05:00:00
  en-cs_hparams_1c:
    name: en-cs_hparams_1c
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      batch_size: 64
    slurm:
      memory: 40G
      time: 05:00:00
  en-cs_hparams_1d:
    name: en-cs_hparams_1d
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      batch_size: 32
    slurm:
      memory: 40G
      time: 05:00:00
