# This is a config file containing experiment runs to be used for hyperparameter searching

# WandB names
wandb:
  project: MTQE
  entity: turing-arc

# The experiments defined in this file will be run once for each of the following seeds
seeds:
  - 42
  - 89
  - 107

# Any params for the slurm file that will be the same across all experiments
slurm:
  account: vjgo8416-mt-qual-est

# These are model parameters that are fixed for each experiment
hparams:
  activations: Tanh
  batch_size: 32
  class_identifier: ced_model
  dropout: 0.1
  encoder_learning_rate: 1.0e-06
  encoder_model: XLM-RoBERTa
  exclude_outliers: 250
  hidden_sizes:
  - 3072
  - 1024
  input_segments:
  - mt
  - src
  keep_embeddings_frozen: false
  layer: mix
  layer_norm: false
  layer_transformation: sparsemax
  layerwise_decay: 0.95
  learning_rate: 1.5e-05
  loss: binary_cross_entropy_with_logits
  loss_lambda: 0.65
  nr_frozen_epochs: 0
  optimizer: AdamW
  pool: avg
  pretrained_model: microsoft/infoxlm-large
  sent_layer: mix
  word_layer: 24
  word_level_training: false

# This is trainer config that is fixed for all experiments
trainer_config:
  deterministic: True
  devices: 1
  max_epochs: 100
  accumulate_grad_batches: 8

# These are the data for each experiment
experiments:
  unfzn_lr_1-5e05_grad8:
    name: unfzn_lr_1-5e05_grad8
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      error_weight: 2
    slurm:
      memory: 40G
      time: 08:00:00
  unfzn_lr_1-5e05_weight2:
    name: unfzn_lr_1-5e05_weight2
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      error_weight: 2
    slurm:
      memory: 40G
      time: 08:00:00
  unfzn_lr_1-5e05_weight3:
    name: unfzn_lr_1-5e05_weight3
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      error_weight: 3
    slurm:
      memory: 40G
      time: 08:00:00
  unfzn_lr_1-5e05_weight4:
    name: unfzn_lr_1-5e05_weight4
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      error_weight: 4
    slurm:
      memory: 40G
      time: 08:00:00
  unfzn_lr_1-5e05_weight5:
    name: unfzn_lr_1-5e05_weight5
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      error_weight: 5
    slurm:
      memory: 40G
      time: 08:00:00
  unfzn_lr_1-5e05_weight6:
    name: unfzn_lr_1-5e05_weight6
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      error_weight: 6
    slurm:
      memory: 40G
      time: 08:00:00
  unfzn_lr_1-5e05_weight7:
    name: unfzn_lr_1-5e05_weight7
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      error_weight: 7
    slurm:
      memory: 40G
      time: 08:00:00
  unfzn_lr_1-5e05_weight8:
    name: unfzn_lr_1-5e05_weight8
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      error_weight: 8
    slurm:
      memory: 40G
      time: 08:00:00
  unfzn_lr_1-5e05_weight9:
    name: unfzn_lr_1-5e05_weight9
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      error_weight: 9
    slurm:
      memory: 40G
      time: 08:00:00
  unfzn_lr_1-5e05_weight10:
    name: unfzn_lr_1-5e05_weight10
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      error_weight: 10
    slurm:
      memory: 40G
      time: 08:00:00
  unfzn_lr_1-5e05_weight11:
    name: unfzn_lr_1-5e05_weight11
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      error_weight: 11
    slurm:
      memory: 40G
      time: 08:00:00
  unfzn_lr_1-5e05_weight12:
    name: unfzn_lr_1-5e05_weight12
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      error_weight: 12
    slurm:
      memory: 40G
      time: 08:00:00
  unfzn_lr_1-5e05_weight13:
    name: unfzn_lr_1-5e05_weight13
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      error_weight: 13
    slurm:
      memory: 40G
      time: 08:00:00
  unfzn_lr_1-5e05_weight14:
    name: unfzn_lr_1-5e05_weight14
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      error_weight: 14
    slurm:
      memory: 40G
      time: 08:00:00
  unfzn_lr_1-5e05_weight15:
    name: unfzn_lr_1-5e05_weight15
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      error_weight: 15
    slurm:
      memory: 40G
      time: 08:00:00
