# This is a config file containing experiment runs to be used for hyperparameter searching

# WandB names
wandb:
  project: MTQE
  entity: turing-arc

# The experiments defined in this file will be run once for each of the following seeds
seeds:
  - 42

# Any params for the slurm file that will be the same across all experiments
slurm:
  account: vjgo8416-mt-qual-est

# These are model parameters that are fixed for each experiment
hparams:
  activations: Tanh
  batch_size: 32
  class_identifier: ced_model
  dropout: 0.2
  encoder_model: XLM-RoBERTa
  final_activation: sigmoid
  hidden_sizes:
  - 3072
  - 1024
  input_segments:
  - mt
  - src
  layer: mix
  layer_norm: false
  layer_transformation: sparsemax
  layerwise_decay: 0.95
  loss: cross-entropy
  loss_lambda: 0.65
  nr_frozen_epochs: 0
  optimizer: AdamW
  pool: avg
  pretrained_model: microsoft/infoxlm-large
  sent_layer: mix
  word_layer: 24
  word_level_training: false

# This is trainer config that is fixed for each experiment
trainer_config:
  deterministic: True
  devices: 1
  max_epochs: 100
  accumulate_grad_batches: 4

# These are the data for each experiment
experiments:
  en-cs_hparams_7a:
    name: en-cs_hparams_7a
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      keep_embeddings_frozen: true
      learning_rate: 1.5e-05
    slurm:
      memory: 40G
      time: 05:00:00
  en-cs_hparams_7b:
    name: en-cs_hparams_7b
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      dropout: 0.2
      keep_embeddings_frozen: false
      learning_rate: 1.5e-05
      encoder_learning_rate: 1.0e-06
    slurm:
      memory: 40G
      time: 05:00:00
  en-cs_hparams_7c:
    name: en-cs_hparams_7c
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      dropout: 0.2
      keep_embeddings_frozen: false
      learning_rate: 1.5e-06
      encoder_learning_rate: 1.0e-07
    slurm:
      memory: 40G
      time: 05:00:00
  en-cs_hparams_7d:
    name: en-cs_hparams_7d
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      dropout: 0.2
      keep_embeddings_frozen: false
      learning_rate: 1.5e-07
      encoder_learning_rate: 1.0e-08
    slurm:
      memory: 40G
      time: 05:00:00
