# This is a config file containing experiment runs to be used for hyperparameter searching

# WandB names
wandb:
  project: MTQE
  entity: turing-arc

# The experiments defined in this file will be run once for each of the following seeds
seeds:
  - 42

# Any params for the slurm file that will be the same across all experiments
slurm:
  account: vjgo8416-mt-qual-est

# These are model parameters that are fixed for each experiment
hparams:
  activations: Tanh
  batch_size: 64
  class_identifier: ced_model
  encoder_model: XLM-RoBERTa
  exclude_outliers: 250
  final_activation: sigmoid
  hidden_sizes:
  - 3072
  - 1024
  input_segments:
  - mt
  - src
  keep_embeddings_frozen: false
  layer: mix
  layer_norm: false
  layer_transformation: sparsemax
  layerwise_decay: 0.95
  loss: cross-entropy
  loss_lambda: 0.65
  nr_frozen_epochs: 0
  optimizer: AdamW
  pool: avg
  pretrained_model: microsoft/infoxlm-large
  sent_layer: mix
  word_layer: 24
  word_level_training: false

# This is trainer config that is fixed for each experiment
trainer_config:
  deterministic: True
  devices: 1
  max_epochs: 200
  accumulate_grad_batches: 4

# These are the data for each experiment
experiments:
  en-cs_hparams_11a:
    name: en-cs_hparams_11a
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      dropout: 0.1
      learning_rate: 1.5e-06
      encoder_learning_rate: 1.0e-07
    slurm:
      memory: 40G
      time: 08:00:00
  en-cs_hparams_11b:
    name: en-cs_hparams_11b
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      dropout: 0.2
      learning_rate: 1.5e-06
      encoder_learning_rate: 1.0e-07
    slurm:
      memory: 40G
      time: 08:00:00
  en-cs_hparams_11c:
    name: en-cs_hparams_11c
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      dropout: 0.1
      learning_rate: 1.5e-07
      encoder_learning_rate: 1.0e-08
    slurm:
      memory: 40G
      time: 08:00:00
  en-cs_hparams_11d:
    name: en-cs_hparams_11d
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      dropout: 0.2
      learning_rate: 1.5e-07
      encoder_learning_rate: 1.0e-08
    slurm:
      memory: 40G
      time: 08:00:00
  en-cs_hparams_11e:
    name: en-cs_hparams_11e
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      dropout: 0.1
      learning_rate: 1.5e-06
      encoder_learning_rate: 1.0e-07
      oversample_minority: true
    slurm:
      memory: 40G
      time: 08:00:00
  en-cs_hparams_11f:
    name: en-cs_hparams_11f
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      dropout: 0.2
      learning_rate: 1.5e-06
      encoder_learning_rate: 1.0e-07
      oversample_minority: true
    slurm:
      memory: 40G
      time: 08:00:00
  en-cs_hparams_11g:
    name: en-cs_hparams_11g
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      dropout: 0.1
      learning_rate: 1.5e-07
      encoder_learning_rate: 1.0e-08
      oversample_minority: true
    slurm:
      memory: 40G
      time: 08:00:00
  en-cs_hparams_11h:
    name: en-cs_hparams_11h
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      dropout: 0.2
      learning_rate: 1.5e-07
      encoder_learning_rate: 1.0e-08
      oversample_minority: true
    slurm:
      memory: 40G
      time: 08:00:00
