# This is a config file containing experiment runs to be used for hyperparameter searching

# WandB names
wandb:
  project: MTQE
  entity: turing-arc

# The experiments defined in this file will be run once for each of the following seeds
seeds:
  - 42
  - 107

# Any params for the slurm file that will be the same across all experiments
slurm:
  account: vjgo8416-mt-qual-est

# These are model parameters that are fixed for each experiment
hparams:
  activations: Tanh
  batch_size: 64
  class_identifier: ced_model
  encoder_model: XLM-RoBERTa
  exclude_outliers: 250
  hidden_sizes:
  - 3072
  - 1024
  input_segments:
  - mt
  - src
  keep_embeddings_frozen: true
  layer: mix
  layer_norm: false
  layer_transformation: sparsemax
  layerwise_decay: 0.95
  loss_lambda: 0.65
  nr_frozen_epochs: 0
  optimizer: AdamW
  pool: avg
  pretrained_model: microsoft/infoxlm-large
  sent_layer: mix
  word_layer: 24
  word_level_training: false

# This is trainer config that is fixed for each experiment
trainer_config:
  deterministic: True
  devices: 1
  max_epochs: 200
  accumulate_grad_batches: 2

# These are the data for each experiment
experiments:
  en-cs_ce_pretrained_head:
    name: en-cs_ce_pretrained_head
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      dropout: 0.1
      learning_rate: 1.0e-06
      encoder_learning_rate: 1.0e-07
      loss: cross_entropy
      num_sentence_classes: 2
    slurm:
      memory: 40G
      time: 08:00:00
  en-cs_bce_pretrained_head:
    name: en-cs_bce_pretrained_head
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      dropout: 0.1
      learning_rate: 1.0e-06
      encoder_learning_rate: 1.0e-07
      loss: binary_cross_entropy
      final_activation: sigmoid
    slurm:
      memory: 40G
      time: 08:00:00
  en-cs_bce_logits_pretrained_head:
    name: en-cs_bce_logits_pretrained_head
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      dropout: 0.1
      learning_rate: 1.0e-06
      encoder_learning_rate: 1.0e-07
      loss: binary_cross_entropy_with_logits
      calc_threshold: true
    slurm:
      memory: 40G
      time: 08:00:00
  en-cs_ce_random_init:
    name: en-cs_ce_random_init
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      dropout: 0.1
      learning_rate: 1.0e-06
      encoder_learning_rate: 1.0e-07
      loss: cross_entropy
      num_sentence_classes: 2
      random_weights: true
    slurm:
      memory: 40G
      time: 08:00:00
  en-cs_bce_random_init:
    name: en-cs_bce_pretrained_head
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      dropout: 0.1
      learning_rate: 1.0e-06
      encoder_learning_rate: 1.0e-07
      loss: binary_cross_entropy
      final_activation: sigmoid
      random_weights: true
    slurm:
      memory: 40G
      time: 08:00:00
  en-cs_bce_logits_random_init:
    name: en-cs_bce_logits_pretrained_head
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      dropout: 0.1
      learning_rate: 1.0e-06
      encoder_learning_rate: 1.0e-07
      loss: binary_cross_entropy_with_logits
      random_weights: true
      calc_threshold: true
    slurm:
      memory: 40G
      time: 08:00:00
  en-ja_ce_pretrained_head:
    name: en-ja_ce_pretrained_head
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      dropout: 0.1
      learning_rate: 1.0e-06
      encoder_learning_rate: 1.0e-07
      loss: cross_entropy
      num_sentence_classes: 2
    slurm:
      memory: 40G
      time: 08:00:00
  en-ja_bce_pretrained_head:
    name: en-ja_bce_pretrained_head
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      dropout: 0.1
      learning_rate: 1.0e-06
      encoder_learning_rate: 1.0e-07
      loss: binary_cross_entropy
      final_activation: sigmoid
    slurm:
      memory: 40G
      time: 08:00:00
  en-ja_bce_logits_pretrained_head:
    name: en-ja_bce_logits_pretrained_head
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      dropout: 0.1
      learning_rate: 1.0e-06
      encoder_learning_rate: 1.0e-07
      loss: binary_cross_entropy_with_logits
      calc_threshold: true
    slurm:
      memory: 40G
      time: 08:00:00
  en-ja_ce_random_init:
    name: en-ja_ce_random_init
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      dropout: 0.1
      learning_rate: 1.0e-06
      encoder_learning_rate: 1.0e-07
      loss: cross_entropy
      num_sentence_classes: 2
      random_weights: true
    slurm:
      memory: 40G
      time: 08:00:00
  en-ja_bce_random_init:
    name: en-ja_bce_pretrained_head
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      dropout: 0.1
      learning_rate: 1.0e-06
      encoder_learning_rate: 1.0e-07
      loss: binary_cross_entropy
      final_activation: sigmoid
      random_weights: true
    slurm:
      memory: 40G
      time: 08:00:00
  en-ja_bce_logits_random_init:
    name: en-ja_bce_logits_pretrained_head
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-ja
    hparams:
      dropout: 0.1
      learning_rate: 1.0e-06
      encoder_learning_rate: 1.0e-07
      loss: binary_cross_entropy_with_logits
      random_weights: true
      calc_threshold: true
    slurm:
      memory: 40G
      time: 08:00:00
