# This is a config file containing experiment runs to be used for regression testing
# These tests include the early_stopping config, but not model_checkpoint config

# WandB names
wandb:
  project: MTQE
  entity: turing-arc

# The experiments defined in this file will be run once for each of the following seeds
seeds:
  - 42

# Any params for the slurm file that will be the same across all experiments
slurm:
  account: vjgo8416-mt-qual-est

# These are model parameters that are fixed for each experiment
hparams:
  activations: Tanh
  batch_size: 16
  class_identifier: ced_model
  dropout: 0.1
  encoder_learning_rate: 1.0e-06
  encoder_model: XLM-RoBERTa
  hidden_sizes:
  - 3072
  - 1024
  input_segments:
  - mt
  - src
  layer: mix
  layer_norm: false
  layer_transformation: sparsemax
  layerwise_decay: 0.95
  learning_rate: 1.5e-05
  loss: binary_cross_entropy_with_logits
  loss_lambda: 0.65
  nr_frozen_epochs: 0.3
  optimizer: AdamW
  pool: avg
  pretrained_model: microsoft/infoxlm-large
  sent_layer: mix
  word_layer: 24
  word_level_training: false

# This is trainer config that is fixed for each experiment
trainer_config:
  deterministic: True
  devices: 1
  max_epochs: 10

# Config for early stopping callback, fixed for each experiment
early_stopping:
  monitor: val_MCC
  patience: 3
  strict: True
  verbose: False
  mode: max
  min_delta: 0.

weights_path:
  path: /Users/jknight/github_repos/arc-mtqe/checkpoints/regression_tests__en-cs_regression_1__42__20240416_160015/epoch=0-step=468.ckpt

# These are the data for each experiment
experiments:
  en-cs_test_model_load:
    name: en-cs_test_model_load
    train_data:
      train_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    dev_data:
      dev_1:
        dataset_name: ced
        language_pairs:
          - en-cs
    hparams:
      keep_embeddings_frozen: true
    slurm:
      memory: 40G
      time: 01:00:00
